#!/bin/sh

clear
echo "This only works on ELF-based Linux."
echo " If it breaks, you get BOTH shiny pieces."
echo " Yes, we need a makefile."
echo " Attempting to build a dynamic BASIClib..."

gcc -Wall -fPIC -c *.c
gcc -shared -Wl,-soname,libBASIC.so.0 -o libBASIC.so.0.0.1 *.o
ln -sf libBASIC.so.0.0.1 libBASIC.so.0
ln -sf libBASIC.so.0 libBASIC.so

# end of makelib ...

